version: "3.7"
name: academy-lms
services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    command: bash /workspace/init.sh
    environment:
      - SHELL=/bin/bash
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - SITE_NAME=${SITE_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DEVELOPER_MODE=${DEVELOPER_MODE}
      - NODE_VERSION_DEVELOP=${NODE_VERSION_DEVELOP}
      - LMS_REPO_URL=${LMS_REPO_URL}
      - AI_TUTOR_REPO_URL=${AI_TUTOR_REPO_URL}
    working_dir: /home/frappe
    volumes:
      - .:/workspace
      - ./.ssh:/workspace/ssh:ro
    ports:
      - 8000:8000
      - 9000:9000
    depends_on:
      - mariadb
      - redis

volumes:
  mariadb-data:
