version: "3.7"
name: academy-lms-production
services:
  mariadb:
    image: mariadb:10.8
    restart: unless-stopped
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
      # Production optimizations
      - --innodb-buffer-pool-size=1G
      - --innodb-log-file-size=256M
      - --innodb-flush-log-at-trx-commit=2
      - --max-connections=200
      - --query-cache-type=0
      - --query-cache-size=0
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  frappe:
    image: frappe/bench:latest
    restart: unless-stopped
    command: bash /workspace/production-init.sh
    environment:
      - SHELL=/bin/bash
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - SITE_NAME=${SITE_NAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - DEVELOPER_MODE=0  # Force production mode
      - NODE_VERSION_DEVELOP=${NODE_VERSION_DEVELOP}
      - LMS_REPO_URL=${LMS_REPO_URL}
      - AI_TUTOR_REPO_URL=${AI_TUTOR_REPO_URL}
      - AI_TUTOR_API_URL=${AI_TUTOR_API_URL}
    working_dir: /home/frappe
    volumes:
      - .:/workspace
      - ./.ssh:/workspace/ssh:ro
      - frappe-data:/home/frappe/frappe-bench  # Persistent data
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - default
      - langchain-network  # Keep the same network for langchain communication
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/method/ping"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 120s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - frappe-data:/var/www/html:ro
    depends_on:
      - frappe
    networks:
      - default
    profiles:
      - with-nginx  # Optional service, enable with --profile with-nginx

volumes:
  mariadb-data:
  redis-data:
  frappe-data:  # Persistent storage for frappe bench

networks:
  langchain-network:
    external: true
    name: academy-langchain_langchain-network  # Same network as development
